services:
  monkey-bky_arm:
    build:
      context: ./
      dockerfile: "Dockerfile"
    image: "monkey/humble:bky_arm"
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    #runtime: nvidia # GPU
    environment:
      # Displays
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIB_GL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
      # GPU
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    user: "root"
    volumes:
      # Docker display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      # Copy Paste from Host
      # - ./bky_ws:/root/bky_ws
      # Device
      - /dev:/dev
      